# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""LLM classifier signal types for experimental deterministic routing."""

from switchyard.lib.processors.llm_classifier.presets import (
    CODING_AGENT_CLASSIFIER_SYSTEM_PROMPT,
    OPENCLAW_CLASSIFIER_SYSTEM_PROMPT,
    LLMClassifierPresets,
    LLMClassifierProfile,
)
from switchyard.lib.processors.llm_classifier.request_processor import (
    DEFAULT_CLASSIFIER_SYSTEM_PROMPT,
    DEFAULT_MAX_REQUEST_CHARS,
    ClassifierCompletion,
    LLMClassifierClient,
    LLMClassifierConfig,
    LLMClassifierError,
    LLMClassifierRequestProcessor,
    OpenAIChatLLMClassifierClient,
    parse_route_decision,
    parse_route_signals,
)
from switchyard.lib.processors.llm_classifier.signals import (
    CTX_DETERMINISTIC_ROUTE_SIGNALS,
    ChannelKind,
    CodeModificationScope,
    CodingAgentRouteDecision,
    CodingAgentTurnType,
    Complexity,
    ContextDependency,
    MemoryDependency,
    OpenClawRouteDecision,
    OpenClawTurnType,
    PrecisionRequirement,
    ReasonCode,
    ReasoningDepth,
    RiskLevel,
    RouteDecision,
    RouteSignals,
    RouteTier,
    TaskType,
)
from switchyard.lib.processors.llm_classifier.tier_selector_request_processor import (
    CTX_DETERMINISTIC_TIER_DECISION,
    SignalTierSelectorConfig,
    SignalTierSelectorRequestProcessor,
    TierSelectionDecision,
)

__all__ = [
    "CODING_AGENT_CLASSIFIER_SYSTEM_PROMPT",
    "CTX_DETERMINISTIC_ROUTE_SIGNALS",
    "CTX_DETERMINISTIC_TIER_DECISION",
    "ChannelKind",
    "ClassifierCompletion",
    "CodeModificationScope",
    "CodingAgentRouteDecision",
    "CodingAgentTurnType",
    "Complexity",
    "ContextDependency",
    "DEFAULT_CLASSIFIER_SYSTEM_PROMPT",
    "DEFAULT_MAX_REQUEST_CHARS",
    "LLMClassifierClient",
    "LLMClassifierConfig",
    "LLMClassifierError",
    "LLMClassifierPresets",
    "LLMClassifierProfile",
    "LLMClassifierRequestProcessor",
    "MemoryDependency",
    "OPENCLAW_CLASSIFIER_SYSTEM_PROMPT",
    "OpenAIChatLLMClassifierClient",
    "OpenClawRouteDecision",
    "OpenClawTurnType",
    "PrecisionRequirement",
    "ReasonCode",
    "ReasoningDepth",
    "RiskLevel",
    "RouteDecision",
    "RouteSignals",
    "RouteTier",
    "SignalTierSelectorConfig",
    "SignalTierSelectorRequestProcessor",
    "TaskType",
    "TierSelectionDecision",
    "parse_route_decision",
    "parse_route_signals",
]
